# Generated by Django 5.0.6 on 2024-06-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_warehouse_product_warehouse_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Processing'), (2, 'Delivered'), (3, 'Cancelled')], default=1),
        ),
    ]
